### ISSUE TITLE
Complete the 'about the app' section in the readMe

### ISSUE THREAD

**Issue by dmayers96** [EDGENortheastern/dan-m-dec22#9]

**Comment by missKatiaPunter** [comment]
@dmayers96 heads up - if you called a ticket Complete the documentation do not merge it until you completed at least something. Also call tickets "complete the project management chapter of the documentation" and so on. Make smaller tickets. One feature -> one ticket -> one branch ->.one PR

**Comment by dmayers96** [comment]
This issue has been completed and linked to a pull request.

**Comment by dmayers96** [comment]
This issue has been completed and linked to a pull request.
